name: Get Zotero Items and Put Into Asciidoc Files

# Run every hour, at minute HH:13
on:
  schedule:
  - cron:  '13 * * * *'

jobs:
  get-zotero-items:
    runs-on: ubuntu-latest

    steps:
    - name: Run HTTP request on Zotero API
      id: zotero_request
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.zotero.org/groups/1607464/collections/PUEWSLWI/items?sort=date&format=bibtex'
        method: 'GET'

    - name: Store Zotero API response in bibtex file
      env:
        ZOTERO_API_RESPONSE: ${{ steps.zotero_request.outputs.response }}
      run: |
        mkdir zotero
        cat "$ZOTERO_API_RESPONSE" > zotero/selection-academic.bibtex

    - name: Upload bibtex file
      uses: actions/upload-artifact@v1
      with:
        name: zotero
        path: zotero
    
  put-items-in-asciidoc:
    needs: get-zotero-items
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repository
      uses: actions/checkout@v2
