name: Get Zotero Items and Put Into Asciidoc Files

# Run every hour, at minute HH:13
on:
  schedule:
  - cron:  '13 * * * *'

jobs:
  get-zotero-items:
    runs-on: ubuntu-latest

    steps:
    - name: Create zotero dir
      run: mkdir zotero

    - name: Curl bibtex file using Zotero API
      uses: wei/curl@v1.1.1
      with:
        args: --output zotero/selection-academic.bib "https://api.zotero.org/groups/1607464/collections/PUEWSLWI/items?sort=date&format=bibtex"

    - name: Upload bibtex file
      uses: actions/upload-artifact@v1
      with:
        name: zotero
        path: zotero
    
  put-items-in-asciidoc:
    needs: get-zotero-items
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repository
      uses: actions/checkout@v2
